language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yoyonel
  password:
    secure: MvXkjY1syzZAEt9OudAoOZUHOhBWucrnZF+79tqbrl4Wi80svuSPylrfitxNgTAv5W8vEd0L1iPn2Q+IddUa9uOu+2ebUziAH6be0G4QcEX5voMM7xLbnAdc8uBSAWXUjMzaMv3FVRtvDeqT1EPqc+bmZpqG/U8tJJc3RN7XrK8z9gL1T237VohOKz99NxsTcwr2ILjAj7Gt3URc4rkn6Ia3ZOoYjhXaHs5BsGtfCORAMSLIZ2+5sIGYTjq0GnryFLnUzcrcKUHObZ7nSMnAIbHxCe+nswu5e8E448X9AC9egibJfcujZ7JOYGSz8qUH9mWgtNsFOsCJYk75c5n0vwhKnqtB74knCeEe1t6DZHMoZHJHD10sAGZwjAZjPDMbER2dn9hq1K6Ff39eXu8BgcJxjK4GtayB87Tvgu+y03GDF2YvpdS+ucThj4uymvmuwQNYMCYM5QZprr+hnZTCM8j1qcHAf2p8zWlCyDlnBD3ErPOsj1iTE6ryySKoW1/f2laLmNGSZ4AbJ4JeNTclJgKTCLYOO2p8PxvpySLqntsiOERIEF6wA4MMv4eooMfJOj/gjDVBdi+Q7f7xltrJTfTfNTwxBrqucj4sMUxDUqa5fcAfoZdI24PHfk0hGZaEgxplfipUfkFAbhAmX4gsujTIT1Pywas9H9FU+QIsbO8=
  on:
    tags: true
    repo: yoyonel/pydarknetserver
    python: 3.7
after_success:
    — coveralls
